---
# This role will install grafana service on server.

- name: Install grafana package
  package:
    name: "{{ grafana_src }}"
    state: present

- name: Allow incoming TCP traffic on ports
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
  loop: "{{ grafana_ports }}"

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Start and enable grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Add prometheus data source
  grafana_datasource:
    name: RabbitMQ
    grafana_url: "{{ grafana_url }}"
    is_default: yes
    ds_type: prometheus
    ds_url: "{{ grafana_prometheus_url }}"

- name: Create local.yml file
  template:
    src: local.yml.j2
    dest: /etc/grafana/provisioning/dashboards/local.yml
    group: "{{ grafana_group }}"
    owner: "{{ grafana_user }}"

- name: Create dirrectory for grafana
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ grafana_group }}"
    owner: "{{ grafana_user }}"
  loop: "{{ grafana_directories }}"

- name: Move grafana dashboards to proper folder
  copy:
    src: "{{ item }}"
    dest: /var/lib/grafana/dashboards/
    group: "{{ grafana_group }}"
    owner: "{{ grafana_user }}"
  loop: "{{ grafana_dashboards }}"

- name: Reboot the machine
  reboot: