---
# This role will install rabbitMQ and rabbitmq_management plugin.

- name: Install Erlang package
  package:
    name: "{{ rabbitmq_erlang_src }}"
    state: present

- name: Import key
  rpm_key:
    key: "{{ rabbitmq_key }}"
    state: present

- name: Install rabbitmq
  package:
    name: "{{ rabbitmq_src }}"
    state: present

- name: Allow incoming TCP traffic on ports
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
  loop: "{{ rabbitmq_ports }}"

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Start rabbitmq and enable to start automatically on reboots.
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Install rabbitmq_management plugin
  rabbitmq_plugin:
    names: "{{ rabbitmq_plugins }}"
    state: enabled

- name: Give rights to rabbitmq
  file:
    path: "{{ rabbitmq_path }}"
    owner: "{{ rabbitmq_user }}"
    group: "{{ rabbitmq_group }}"
    recurse: yes

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ rabbitmq_packages }}"

- name: Install requests via pip
  pip:
    name: "{{ rabbitmq_pip_modules }}"
    state: present

- name: Create directory for rabbitmq
  file:
    path: "{{ rabbitmq_directory }}"
    state: directory
    group: "{{ rabbitmq_group }}"
    owner: "{{ rabbitmq_user }}"

- name: Download and unarchive node exporter
  unarchive:
    remote_src: yes
    src: "{{ rabbitmq_node_exporter_source }}"
    dest: "{{ rabbitmq_directory }}"

- name: Create user for node exporter service
  user:
    name: "{{ rabbitmq_node_exporter_user }}"
    create_home: no
    shell: /bin/false
    state: present

- name: Move node exporter file to bin folder
  copy:
    src: "{{ rabbitmq_node_exporter_directory }}"
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: a+x
    group: "{{ rabbitmq_node_exporter_group }}"
    owner: "{{ rabbitmq_node_exporter_user }}"

- name: Create node exporter service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    group: "{{ rabbitmq_node_exporter_group }}"
    owner: "{{ rabbitmq_node_exporter_user }}"

- name: Start and enable rabbitmq exporter service
  systemd:
    name: node_exporter
    daemon_reload: yes
    state: started
    enabled: yes

- name: Download and unarchive rabbitmq exporter
  unarchive:
    remote_src: yes
    src: "{{ rabbitmq_exporter_source }}"
    dest: "{{ rabbitmq_directory }}"

- name: Create user for rabbitmq exporter service
  user:
    name: "{{ rabbitmq_exporter_user }}"
    create_home: no
    shell: /bin/false
    state: present

- name: Move rabbitmq exporter file to bin folder
  copy:
    src: "{{ rabbitmq_exporter_directory }}"
    dest: /usr/local/bin/rabbitmq_exporter
    remote_src: yes
    mode: a+x
    group: "{{ rabbitmq_exporter_group }}"
    owner: "{{ rabbitmq_exporter_user }}"

- name: Create rabbitmq exporter service
  template:
    src: rabbitmq_exporter.service.j2
    dest: /etc/systemd/system/rabbitmq_exporter.service
    group: "{{ rabbitmq_exporter_group }}"
    owner: "{{ rabbitmq_exporter_user }}"

- name: Start and enable rabbitmq exporter service
  systemd:
    name: rabbitmq_exporter
    daemon_reload: yes
    state: started
    enabled: yes