---
# This role will install rabbitMQ and rabbitmq_management plugin.
- name: Install wget
  yum:
    name: wget
    state: present

#- name: Install epel repository
#  yum:
#    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#    state: present

#- name: Install remi repository
#  yum:
#   name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
#    state: present

- name: Install Erlang package
  yum:
    name: https://packages.erlang-solutions.com/erlang/rpm/centos/7/x86_64/esl-erlang_23.2-1~centos~7_amd64.rpm
    state: present

- name: Import key
  rpm_key:
    state: present
    key: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc

- name: Install rabbitmq
  yum:
    name: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.9.5/rabbitmq-server-3.9.5-1.el7.noarch.rpm
    state: present

- name: Allow incoming TCP traffic on ports
  command: firewall-cmd --zone=public --permanent --add-port=4369/tcp --add-port=5671-5672/tcp --add-port=25672/tcp --add-port=15672-15675/tcp  --add-port=61613-61614/tcp --add-port=1883/tcp --add-port=15674/tcp

- name: Reload firewall
  command: firewall-cmd --reload

- name: Start rabbitmq and enable to start automatically on reboots.
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Install rabbitmq_management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled

- name: Give rights to rabbitmq
  command: chown -R rabbitmq:rabbitmq /var/lib/rabbitmq/